[project]
name = "invest-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "akshare>=1.18.8",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "yfinance>=1.0",
]
